version: '3'

services:
  postgres:
    container_name: postgres-tcc
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: database
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"